# This workflow will change the date.txt file and commit it to the repository.
# It is not for PRs. It is to demonstrate

# Info on the action
name: Change file
run-name: ${{ github.actor }} is changing the date.txt file and committing it 🚀

on:
  # Run automatically on main pushes
#  push:
#    branches:
#      - main

  workflow_dispatch:

jobs:
  # As per https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      # Check out the code to be able to deploy
      - name: 'Checking out code'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # change the date.txt file
      - name: 'Change date.txt file'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo $(date) > date.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add date.txt
          git commit -m "Update date.txt"
          git push
